export { default as Dashboard } from './Dashboard';
export { default as Products } from './Products';
export { default as Categories } from './Categories';
export { default as Orders } from './Orders';
export { default as Customers } from './Customers';
export { default as Offers } from './Offers';
export { default as Reports } from './Reports';
export { default as Invoices } from './Invoices';
export { default as Settings } from './Settings';